# Code for dataset folder creation

In [18]:
# Importing the Libraries Required

import os
import string

# Creating the directory Structurel

if not os.path.exists("dataSet2"):
    os.makedirs("dataSet2")

if not os.path.exists("dataSet2/trainingData"):
    os.makedirs("dataSet2/trainingData")

if not os.path.exists("dataSet2/testingData"):
    os.makedirs("dataSet2/testingData")
# if not os.path.exists("dataSet2/testingData/adb"):
#     os.makedirs("dataSet2/testingData/adb")
# if not os.path.exists("dataSet2/trainingData/adb"):
#     os.makedirs("dataSet2/trainingData/adb")

# Making folder  0 (i.e blank) in the training and testing data folders respectively
for i in range(11):
    if not os.path.exists("dataSet2/trainingData/" + str(i)):
        os.makedirs("dataSet2/trainingData/" + str(i))

    if not os.path.exists("dataSet2/testingData/" + str(i)):
        os.makedirs("dataSet2/testingData/" + str(i))

# Making Folders from A to Z in the training and testing data folders respectively

# for i in string.ascii_uppercase:
#     if not os.path.exists("dataSet2/trainingData/" + i):
#         os.makedirs("dataSet2/trainingData/" + i)
    
#     if not os.path.exists("dataSet2/testingData/" + i):
#         os.makedirs("dataSet2/testingData/" + i)

# data collection  when mode is testing - images goto test data folder and vice versa

In [20]:
# Importing the Libraries Required

import cv2
import numpy as np
import os

# Creating and Collecting Training Data

mode = 'testingData'
directory = 'dataSet2/' + mode + '/'
minValue = 35

capture = cv2.VideoCapture(0)
interrupt = -1

while True:
    _, frame = capture.read()

    # Simulating mirror Image

    frame = cv2.flip(frame, 1)

    # Getting count of existing images

    count = {  #change this according to the order you want
#                 'zero': len(os.listdir(directory+"/0")),

                '1': len(os.listdir(directory+"/1")),
                '2': len(os.listdir(directory+"/2")),
                '3': len(os.listdir(directory+"/3")),
                '4': len(os.listdir(directory+"/4")),
                '5': len(os.listdir(directory+"/5")),
                
                
    }

    # Printing the count of each set on the screen
    
#     cv2.putText(frame, "ZERO : " +str(count['zero']), (10, 60), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)
    
    cv2.putText(frame, "1 : " +str(count['1']), (10, 70), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)
    cv2.putText(frame, "2 : " +str(count['2']), (10, 80), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)
    cv2.putText(frame, "3 : " +str(count['3']), (10, 90), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)
    cv2.putText(frame, "4 : " +str(count['4']), (10, 100), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)
    cv2.putText(frame, "5 : " +str(count['5']), (10, 110), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)



    # Coordinates of the ROI
    
    x1 = int(0.5*frame.shape[1])
    y1 = 10
    x2 = frame.shape[1]-10
    y2 = int(0.5*frame.shape[1])

    # Drawing the ROI
    # The increment/decrement by 1 is to compensate for the bounding box
    
    cv2.rectangle(frame, (x1-1, y1-1), (x2+1, y2+1), (255,0,0) ,1)
    
    # Extracting the ROI
    
    roi = frame[y1:y2, x1:x2]

    cv2.imshow("Frame", frame)
    
    # Image Processing

    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    _, roi = cv2.threshold(roi, 120, 255, cv2.THRESH_BINARY)
    cv2.imshow("ROI", roi)

    # Data Collection

    interrupt = cv2.waitKey(10)
    if interrupt & 0xFF == 27: 
        # esc key
        break
#     if interrupt & 0xFF == ord('0'):
#         cv2.imwrite(directory+'0/'+str(count['zero'])+'.jpg', roi)

    if interrupt & 0xFF == ord('1'):
        cv2.imwrite(directory+'1/'+str(count['1'])+'.jpg', roi)
    
    if interrupt & 0xFF == ord('2'):
        cv2.imwrite(directory+'2/'+str(count['2'])+'.jpg', roi)
    
    if interrupt & 0xFF == ord('3'):
        cv2.imwrite(directory+'3/'+str(count['3'])+'.jpg', roi)
    
    if interrupt & 0xFF == ord('4'):
        cv2.imwrite(directory+'4/'+str(count['4'])+'.jpg', roi)
    
    if interrupt & 0xFF == ord('5'):
        cv2.imwrite(directory+'5/'+str(count['5'])+'.jpg', roi)
    
    interrupt = cv2.waitKey(1)
    if interrupt & 0xFF == ord('q'): # esc key
        break
  
    
capture.release()
cv2.destroyAllWindows()


# model train

In [24]:
# Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten , Dropout
from keras.layers import Dense

# Step 1 - Building the CNN

# Initializing the CNN
classifier = Sequential()

# First convolution layer and pooling
classifier.add(Convolution2D(32, (3, 3), input_shape=(64, 64, 1), activation='relu'))
classifier.add(MaxPooling2D(pool_size=(2, 2)))


classifier.add(Dropout(0.25))
# Here 0.25 means we are avoiding 25% of the neurons to avoid overfitting of the data.

# Second convolution layer and pooling
classifier.add(Convolution2D(64, (3, 3), activation='relu'))
# input_shape is going to be the pooled feature maps from the previous convolution layer
classifier.add(MaxPooling2D(pool_size=(2, 2)))

# 3rd
classifier.add(Convolution2D(128, (3, 3), activation='relu'))
# input_shape is going to be the pooled feature maps from the previous convolution layer
classifier.add(MaxPooling2D(pool_size=(2, 2)))

# 4th
classifier.add(Convolution2D(256, (3, 3), activation='relu'))
# input_shape is going to be the pooled feature maps from the previous convolution layer
classifier.add(MaxPooling2D(pool_size=(2, 2)))


# Flattening the layers
classifier.add(Flatten())

# Adding a fully connected layer
classifier.add(Dense(units=128, activation='relu'))
classifier.add(Dense(units=11, activation='softmax')) # softmax for more than 2 categories

# Compiling the CNN
classifier.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']) # categorical_crossentropy for more than 2


# Step 2 - Preparing the train/test data and training the model
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(
        rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory(r'C:\Users\rohitha\Downloads\Sign_Language_Recognition_with_GUI-main\Sign_Language_Recognition_with_GUI-main\dataSet2\trainingData',
                                                 target_size=(64, 64),
                                                 batch_size=10,
                                                 color_mode='grayscale',
                                                 class_mode='categorical')

test_set = test_datagen.flow_from_directory(r'C:\Users\rohitha\Downloads\Sign_Language_Recognition_with_GUI-main\Sign_Language_Recognition_with_GUI-main\dataSet2\testingData',
                                            target_size=(64, 64),
                                            batch_size=5,
                                            color_mode='grayscale',
                                            class_mode='categorical') 
classifier.fit(
        training_set,
        #steps_per_epoch=3300, # No of images in training set
        #steps_per_epoch=820,
        epochs=5,
        validation_data=test_set)



        #validation_steps=110) # No of images in test set
        #validation_steps=715) # No of images in test set


print("done")
# Saving the model
model_json = classifier.to_json()
with open("mew.json", "w") as json_file:
    json_file.write(model_json)
classifier.save_weights('mew.h5')






Found 583 images belonging to 11 classes.
Found 104 images belonging to 11 classes.
Epoch 1/5
59/59 [==============================] - 6s 82ms/step - loss: 1.1913 - accuracy: 0.5540 - val_loss: 3.4886 - val_accuracy: 0.4135
Epoch 2/5
59/59 [==============================] - 5s 75ms/step - loss: 0.0792 - accuracy: 0.9657 - val_loss: 3.8747 - val_accuracy: 0.4038
Epoch 3/5
59/59 [==============================] - 5s 76ms/step - loss: 6.3580e-04 - accuracy: 1.0000 - val_loss: 4.0344 - val_accuracy: 0.4231
Epoch 4/5
59/59 [==============================] - 5s 77ms/step - loss: 2.9587e-04 - accuracy: 1.0000 - val_loss: 4.1845 - val_accuracy: 0.4231
Epoch 5/5
59/59 [==============================] - 5s 76ms/step - loss: 1.9986e-04 - accuracy: 1.0000 - val_loss: 4.2384 - val_accuracy: 0.4231
done


In [7]:
#predict

In [29]:
import numpy as np
from keras.models import model_from_json
import operator
import cv2
import random
import pygame
import glob
import sys, os

# Loading the model
json_file = open("mew.json", "r")
model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(model_json)

# load weights into new model
loaded_model.load_weights("mew.h5")
print("Loaded model from disk")

font = cv2.FONT_HERSHEY_COMPLEX_SMALL

cap = cv2.VideoCapture(0)

# Category dictionary
categories = {1: 'ONE', 2: 'TWO', 3: 'THREE', 4: 'FOUR', 5: 'FIVE'}
#categories = {0: 'ZERO', 1: 'ONE', 2: 'TWO', 3: 'THREE', 4: 'FOUR', 5: 'FIVE','a':'A','b':'B','bstofluck':'All The Best'}
while True:
    _, frame = cap.read()
    height,width = frame.shape[:2]
    # Simulating mirror image
    frame = cv2.flip(frame, 1)
    
    # Got this from collect-data.py
    # Coordinates of the ROI
    x1 = int(0.5*frame.shape[1])
    y1 = 10
    x2 = frame.shape[1]-10
    y2 = int(0.5*frame.shape[1])
    print(x1,x2,y1,y2)
    # Drawing the ROI
    # The increment/decrement by 1 is to compensate for the bounding box
    cv2.rectangle(frame, (x1-1, y1-1), (x2+1, y2+1), (255,0,0) ,1)
    
    # Extracting the ROI
    roi = frame[y1:y2, x1:x2]

    # Resizing the ROI so it can be fed to the model for prediction
    roi = cv2.resize(roi, (64, 64)) 
    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    _, test_image = cv2.threshold(roi, 120, 255, cv2.THRESH_BINARY)
    cv2.imshow("test", test_image)
    # Batch of 1
    result = loaded_model.predict(test_image.reshape(1, 64, 64, 1))
    print(result)

    prediction = {  #this should be in the same order as your dataset folders are, 
        #i tried a different dataset so mine is different
                  #'None' : result[0][0],
                  '1' : result[0][0],
                  '2' : result[0][1],
                  '3' : result[0][2],
                  '4' : result[0][3],
                  '5' : result[0][4],
                  
                 
                 }
    sa =max(result[0]*100)
    #print("\n",sa,result[0])
    
    
    # Sorting based on top prediction
    prediction = sorted(prediction.items(), key=operator.itemgetter(1), reverse=True)
    
    # Displaying the predictions
    cv2.rectangle(frame, (x1, y1+260) , (x2, y2) , (0,0,0),-6)

    if sa>99:
        # Displaying the predictions
        cv2.putText(frame,"  "+prediction[0][0],(x1, y1+290), font, 1,(255,255,255),1,cv2.LINE_AA)

        pred = prediction[0][0]

#         songs = glob.glob("voice/%s.mp3"%pred)
#         song = random.choice(songs)
#         pygame.mixer.init()
#         music = pygame.mixer.music.load(song)
#         pygame.mixer.music.play()
                
#         time = 0
                
#         while (pygame.mixer_music.get_busy()):
#             pygame.time.Clock().tick(10)
#             time+=1
#             if time == 14:
#                 pygame.mixer_music.stop()
#                 time = 0
                    
    cv2.putText(frame, prediction[0][0], (10, 120), cv2.FONT_HERSHEY_PLAIN, 1, (0,255,255), 1)    
    cv2.imshow("Frame", frame)
    
    interrupt = cv2.waitKey(1)
    if interrupt & 0xFF == ord('q'): # esc key
        break
cap.release()
cv2.destroyAllWindows()


Loaded model from disk
320 630 10 320
1/1 [==============================] - 0s 81ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 32ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 22ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 23ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 24ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 19ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 23ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [=====================

1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 20ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 25ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 21ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 20ms/step
[[0. 1. 0. 0

1/1 [==============================] - 0s 13ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 25ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 10ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 21ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 24ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 24ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 19ms/step
[[0. 1. 0. 0

1/1 [==============================] - 0s 20ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 27ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 12ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 21ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 2.5936248e-07 0.0000000e+00
  9.9999976e-01 0.0000000e+00 0.0000000e+00 

1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 33ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 25ms/step
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 24ms/step
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 1.2382542e-24
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 1

1/1 [==============================] - 0s 15ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 17ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 19ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 20ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 33ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 14ms/step
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 20ms/step
[[0. 0. 0. 0

320 630 10 320
1/1 [==============================] - 0s 15ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0.000000e+00 1.000000e+00 0.000000e+00 6.263682e-34 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00]]
320 630 10 320
1/1 [==============================] - 0s 18ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 21ms/step
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
320 630 10 320
1/1 [==============================] - 0s 14ms/step
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.2710451e-19 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]]
320 630 10 320
1/1 [==============================] - 0s 16ms/step
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.2710451e-19 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]]
320 630 10 3